### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/wand#4]
TODO:
- [x] Incorporation of [standard](https://github.com/feross/standard)
- [ ] Documentation both internally and on the wiki
- [x] Organization of cross-team code review
- [x] Unit tests

**Comment by bsmithgall** [comment]
@ErnieAtLYD is going to work on documentation! what a stand-up guy!

**Comment by mapsam** [comment]
![rockclap](https://cloud.githubusercontent.com/assets/1943001/9153097/e9b0282a-3e11-11e5-90cd-7c39446fbaaa.gif)
